# This is a simple configuration.
# If you want to see the full configuration, please check `full-config.toml` .
# And see https://gohugo.io/getting-started/configuration/ .

baseURL = "https://blog.flyingghost.tech/"
title = "子非鬼"



[params]

  tencent_analytics = "66444964"    # Tencent Analytics

  [params.utteranc]         # utteranc is a comment system based on GitHub issues. see https://utteranc.es
    enable = true
    repo = "flyingghost/blog.flyingghost.tech"    # The repo to store comments
    issueTerm = "pathname"

  # [params.livere]          	#LiveRe comment. see https://www.livere.com/
	#   uid = "MTAyMC80NDg0Ni8yMTM2Nw=="